name: Trigger Publish
on:
  repository_dispatch:
    types: [trigger-publish]

  workflow_dispatch:
    inputs:
      release_type:
        description: 'Publish type'
        required: true
        default: 'all'
        type: choice
        options:
          - debug
          - build
          - testpypi
          - pypi
          - all

jobs:
  trigger_publish:
    uses: ./.github/workflows/workflows.yml
    with:
      working-directory: 'repo_codes'
      release_type: ${{ github.event.inputs.release_type }} || ${{ github.event.client_payload.release_type }} || 'debug'
    secrets:
      REPO_DISPATCH_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
